### ISSUE TITLE
Next and prev to any image

### ISSUE THREAD

**Issue by schvabodka-man** [johanclaesson/picpocket#2] opened 2017-08-30 11:59 UTC
For some reason at the current moment picpocket jumps only to the same file type image(i.e if i've opened png image it will jump to next png, even if there is some jpegs). How can i fix it?

**Comment by johanclaesson** [comment] 2017-08-30 21:26
Hi,
Ok, and is it the same with other types - if you start at a jpeg file
it will jump to other jpeg files?  Or jpeg files will never show
up?

Which version of Emacs is this and on which platform?

Can you also share the values of variables picpocket-version,
picpocket-picture-regexp and image-type-file-name-regexps?

**Comment by schvabodka-man** [comment] 2017-08-31 07:43
Yes, it's same with all file types. When i start with gif it only jumps to gif, when with jpg - to jpg, etc.
Emacs 25, Fedora. picpocket is newest version from melpa, variables are defaults. Actually the most funniest part that it only works like that only in some directories. Sometimes it works okay and jumps just to other picture file. Maybe it's somehow releated to this hooks
```
(add-hook 'image-mode-hook 'picpocket)
(add-hook 'image-minor-mode-hook 'picpocket)
```

**Comment by johanclaesson** [comment] 2017-09-02 15:25
Ok, i have so far been unable to reproduce this behaviour.

Regarding the hooks i suppose the purpose is to replace
image-mode with picpocket.  That should kind of work even though
picpocket was not quite designed with this usage in mind.  In
particular there is currently only one global *picpocket* buffer.

An alternative to adding those hooks would be
to alter auto-mode-alist like this:

```
(require 'cl-lib)
(setq auto-mode-alist
      (cl-loop for (regexp . mode) in auto-mode-alist
               if (eq mode 'image-mode)
               collect (cons regexp #'picpocket)
               else
               collect (cons regexp mode)))
```

This will call picpocket earlier compared to those hooks.  I am
curious if this will avoid the strange behaviour.  But this is
just a wild guess.

I am still interested in the values of:

picpocket-picture-regexp

image-type-file-name-regexps

These variables are not entirely static.  Picpocket mode will
alter them.  So even if you have not changed them explicitly
their values are of interest.

I should also clarify that it is the buffer-local values of these
variables in the *picpocket* buffer when the weird behavior occur
that i request.

Also a question: The second number in the header line in
picpocket mode is supposed to be the number of pictures.  When it
is locked up on say png images does this number reflect the
number of png images in the directory?  Or the total number of images?

**Comment by schvabodka-man** [comment] 2017-09-03 10:35
It reflects total number of pictures. The hook loads picpocket nice but it actually doesn't help with this problem.
picpocket-picture regexp

`"\\.\\(?:3fr\\|a\\(?:r[tw]\\|vs\\)\\|bmp[23]?\\|c\\(?:als?\\|myka?\\|r[2w]\\|u[rt]\\)\\|d\\(?:c[mrx]\\|ds\\|ng\\|px\\)\\|exr\\|f\\(?:ax\\|its\\)\\|gif\\(?:87\\)?\\|hrz\\|ic\\(?:on\\|[bo]\\)\\|j\\(?:2c\\|ng\\|p\\(?:eg\\|[2cg]\\)\\)\\|k\\(?:25\\|dc\\)\\|m\\(?:iff\\|ng\\|rw\\|s\\(?:l\\|vg\\)\\|tv\\)\\|nef\\|o\\(?:rf\\|tb\\)\\|p\\(?:bm\\|c\\(?:ds\\|[dltx]\\)\\|db\\|ef\\|gm\\|i\\(?:ct\\|x\\)\\|jpeg\\|n\\(?:g\\(?:24\\|32\\|8\\)\\|[gm]\\)\\|pm\\|sd\\|tif\\|wp\\)\\|r\\(?:a[fs]\\|gb[ao]?\\|l[ae]\\)\\|s\\(?:c[rt]\\|fw\\|gi\\|r[2f]\\|un\\|vgz?\\)\\|t\\(?:ga\\|i\\(?:ff\\(?:64\\)?\\|le\\|m\\)\\|tf\\)\\|uyvy\\|v\\(?:da\\|i\\(?:car\\|d\\|ff\\)\\|st\\)\\|w\\(?:bmp\\|pg\\)\\|x\\(?:3f\\|bm\\|cf\\|pm\\|wd\\|[cv]\\)\\|y\\(?:cbcra?\\|uv\\)\\)\\'"`

Image type file

```
(("\\.png\\'" . png)
 ("\\.gif\\'" . gif)
 ("\\.jpe?g\\'" . jpeg)
 ("\\.bmp\\'" . bmp)
 ("\\.xpm\\'" . xpm)
 ("\\.pbm\\'" . pbm)
 ("\\.xbm\\'" . xbm)
 ("\\.ps\\'" . postscript)
 ("\\.tiff?\\'" . tiff)
 ("\\.svgz?\\'" . svg)
 ("\\.\\(?:3fr\\|a\\(?:r[tw]\\|vs\\)\\|bmp[23]?\\|c\\(?:als?\\|myka?\\|r[2w]\\|u[rt]\\)\\|d\\(?:c[mrx]\\|ds\\|ng\\|px\\)\\|exr\\|f\\(?:ax\\|its\\)\\|gif\\(?:87\\)?\\|hrz\\|ic\\(?:on\\|[bo]\\)\\|j\\(?:2c\\|ng\\|p\\(?:eg\\|[2cg]\\)\\)\\|k\\(?:25\\|dc\\)\\|m\\(?:iff\\|ng\\|rw\\|s\\(?:l\\|vg\\)\\|tv\\)\\|nef\\|o\\(?:rf\\|tb\\)\\|p\\(?:bm\\|c\\(?:ds\\|[dltx]\\)\\|db\\|ef\\|gm\\|i\\(?:ct\\|x\\)\\|jpeg\\|n\\(?:g\\(?:24\\|32\\|8\\)\\|[gm]\\)\\|pm\\|sd\\|tif\\|wp\\)\\|r\\(?:a[fs]\\|gb[ao]?\\|l[ae]\\)\\|s\\(?:c[rt]\\|fw\\|gi\\|r[2f]\\|un\\|vgz?\\)\\|t\\(?:ga\\|i\\(?:ff\\(?:64\\)?\\|le\\|m\\)\\|tf\\)\\|uyvy\\|v\\(?:da\\|i\\(?:car\\|d\\|ff\\)\\|st\\)\\|w\\(?:bmp\\|pg\\)\\|x\\(?:3f\\|bm\\|cf\\|pm\\|wd\\|[cv]\\)\\|y\\(?:cbcra?\\|uv\\)\\)\\'" . imagemagick))

```

**Comment by johanclaesson** [comment] 2017-09-05 21:02
Ok, thanks.  I just pushed a new version of picpocket (version 38 or 20170905.1133 on melpa).
The command picpocket-dump will in this version print debug info in a buffer `*picpocket-dump*`
(this includes all file names in the current directory).  Please reproduce the problem and run M-x picpocket-dump in the picpocket buffer.  Then copy the content of the `*picpocket-dump*` buffer and attach it here or mail it to johanclaesson [at] bredband.net.

**Comment by schvabodka-man** [comment] 2017-09-07 05:50
Funny how but pictures are actually loading and opening but in wrong order. Here is dump anyway
https://paste.ee/p/nOm0H
I cleaned up it a little bit(from dir files) for oblivious reasons

**Comment by johanclaesson** [comment] 2019-08-21 12:51
Hi,

I still cannot reproduce this.  If this still bothers you please try
and reproduce it without any customization.  That is start emacs with the -Q
option and load picpocket with a command such as the following:

(load "~/.emacs.d/elpa/picpocket-20180914.1819/picpocket.el")

After that run picpocket in some directory which have the problem.
Is the bug reproducible in this way?

Regards,

/Johan

**Comment by johanclaesson** [comment] 2021-01-04 15:36
Hi,
I guess now is probably a good time to close this issue. :)
Regards and belated Happy New Year,
/Johan

**Closed as completed by johanclaesson** 2021-01-04 15:36 UTC
